[services.frontend]
path = "vacantes-front"
build = "npm install && npm run build"
start = "serve -s dist -l 5000"
type = "node"

[services.backend]
path = "back"
build = "npm install"
start = "npm start"
type = "node"
