[services.frontend]
  path = "vacantes-front"
  dockerfile = "./vacantes-front/Dockerfile"
  build = "npm install && npm run build"
  start = "serve -s dist -l 5000"
  type = "node"

[services.backend]
  path = "back"
  dockerfile = "./back/Dockerfile"
  build = "npm install"
  start = "npm start"
  type = "node"
